//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Personal
    {
        public int ID_personal { get; set; }

        [StringLength(50, ErrorMessage = "El Nombre no puede contener mas de 50 caracteres.")]
        [Required]
        public string Nombre { get; set; }

        [StringLength(50, ErrorMessage = "El Apellido Paterno no puede contener mas de 50 caracteres.")]
        [Display(Name = "Apellido Paterno")]
        [Required]
        public string ApePaterno { get; set; }

        [StringLength(50, ErrorMessage = "El Apellido Materno no puede contener mas de 50 caracteres.")]
        [Display(Name = "Apellido Materno")]
        [Required]
        public string ApeMaterno { get; set; }
        [Required]
        [Range(1,100, ErrorMessage ="Debe ser una Edad valida ")]
        public Nullable<int> Edad { get; set; }
        [Required]
        public Nullable<bool> IsActive { get; set; }
    }
}
